CREATE DATABASE Colegio

USE Colegio


CREATE TABLE Alucmno (
CODIGO VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDOS VARCHAR(50),
CURSO VARCHAR (30),
NOTA1 FLOAT,
NOTA2 FLOAT,
NOTA3 FLOAT,
FINAL FLOAT,
PROMEDIO FLOAT,
 OBSERVACIONES varchar(50)
)

select * from Alucmno